services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: store
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "33306:3306"
    volumes:
      - store-db-data:/var/lib/mysql

  flaskapp:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASSWORD: flaskpass
      DB_NAME: store
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

volumes:
  store-db-data:
